name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.0'
    - name: Build kolibri
      run: |
        cd kolibri
        mkdir build
        cd build
        qmake ..
        make
    - name: Build kolibri_test
      run: |
        cd kolibri_test
        mkdir build
        cd build
        qmake ..
        make
    - name: Run Tests
      run: |
        cd kolibri_test/build
        ./kolibri_test
