name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.6.0'
    - name: Build main project
      run: |
        cd kolibri
        mkdir build
        cd build
        qmake ..
        make
    - name: Build tests
      run: |
        cd kolibri_tests
        mkdir build
        cd build
        qmake ..
        make
