name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.0'
    - name: Build
      run: |
        mkdir build
        cd build
        qmake ..
        make

  Test:    
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
      - name: Test
        run: |
           mkdir build
           cd build
           qmake ..
           make       
